# Generated by Django 5.2.1 on 2025-06-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_count', models.PositiveSmallIntegerField()),
                ('room_type', models.CharField(choices=[('STUDIO', 'Студия'), ('ONE_BEDROOM', 'Одна спальня'), ('TWO_BEDROOM', 'Две спальни'), ('TWO_BEDROOM_ENSUITE', 'Две спальни с отдельными ванными'), ('THREE_BEDROOM', 'Три спальни'), ('ENTIRE_HOUSE', 'Дом целиком'), ('COTTAGE', 'Коттедж'), ('PENTHOUSE', 'Пентхаус'), ('WG_ZIMMER', 'Комната в общей квартире (WG)'), ('SHARED_ROOM', 'Общая комната / койко-место'), ('LOFT', 'Лофт / Мансарда'), ('APARTMENT_WITH_TERRACE', 'Квартира с террасой/балконом')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['price'], name='rent_offer_price_f85594_idx'), models.Index(fields=['room_type'], name='rent_offer_room_ty_fb3cb8_idx'), models.Index(fields=['rooms_count'], name='rent_offer_rooms_c_61ddc7_idx'), models.Index(fields=['location'], name='rent_offer_locatio_7071f5_idx')],
            },
        ),
    ]
