# Generated by Django 5.2.1 on 2025-06-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rent.offer', verbose_name='Предложение'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['offer'], name='core_review_offer_i_9a9026_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author'], name='core_review_author__9f8869_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='core_review_created_25a366_idx'),
        ),
    ]
